apiVersion: v1
kind: Service
metadata:
  name: counter
spec:
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
  selector:
    app: counter

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: counter-service
# spec:
#   type: NodePort
#   selector:
#     app: counter
#   ports:
#     - port: 8000
#       name: http
#       nodePort: 30000